/******************************************************************************
;	ノーマルテキスト
******************************************************************************/
package sio29.jzeditor.backends.j2d;

import sio29.ulib.udlgbase.backends.j2d.udlg.actiontool.*;

public class JzEditorActionInfo{
	public final static ActionInfo[] g_actioninfo_tbl={
		new ActionInfo(JzEditorAction.New				,"新規作成"),
		new ActionInfo(JzEditorAction.NewWindow			,"新規ウィンドウに新規作成"),
		new ActionInfo(JzEditorAction.Open				,"開く"),
		new ActionInfo(JzEditorAction.OpenWindow		,"新規ウィンドウに開く"),
		new ActionInfo(JzEditorAction.OpenAdd			,"既存のファイルへ追加"),
		new ActionInfo(JzEditorAction.OpenOutter		,"新規ファイルを外部エディタで開く"),
		new ActionInfo(JzEditorAction.OpenOutterNow		,"現在のファイルを外部エディタで開く"),
		new ActionInfo(JzEditorAction.OuterFiler		,"外部ファイラー"),
		new ActionInfo(JzEditorAction.Save				,"上書き保存"),
		new ActionInfo(JzEditorAction.SaveAs			,"名前を付けて保存"),
		new ActionInfo(JzEditorAction.CloseTab			,"タブを閉じる"),
		new ActionInfo(JzEditorAction.CloseAllTab		,"全てのタブを閉じる"),
		new ActionInfo(JzEditorAction.OpenCommandLine	,"コマンドラインを開く"),
		new ActionInfo(JzEditorAction.Print				,"印刷"),
		new ActionInfo(JzEditorAction.DocInfo			,"文章の情報"),
		new ActionInfo(JzEditorAction.Exit				,"終了"),
		new ActionInfo(JzEditorAction.Undo				,"元に戻す"),
		new ActionInfo(JzEditorAction.Redo				,"やり直し"),
		new ActionInfo(JzEditorAction.SelectAll			,"全て選択"),
		new ActionInfo(JzEditorAction.SelectClear		,"選択クリア"),
		new ActionInfo(JzEditorAction.BlockSelect		,"矩形選択"),
		new ActionInfo(JzEditorAction.TagJump			,"タグジャンプ"),
		new ActionInfo(JzEditorAction.TagJumpOutter		,"外部エディタでタグジャンプ"),
		new ActionInfo(JzEditorAction.JumpTop			,"文章の先頭へ"),
		new ActionInfo(JzEditorAction.JumpBottom		,"文章の最後へ"),
		new ActionInfo(JzEditorAction.JumpLineTop		,"行頭へ"),
		new ActionInfo(JzEditorAction.JumpLineBottom	,"行末へ"),
		new ActionInfo(JzEditorAction.Cut				,"切り取り"),
		new ActionInfo(JzEditorAction.Copy				,"コピー"),
		new ActionInfo(JzEditorAction.Paste				,"貼り付け"),
		new ActionInfo(JzEditorAction.ToolBar			,"ツールバー"),
		new ActionInfo(JzEditorAction.StatusBar			,"ステータスバー"),
		new ActionInfo(JzEditorAction.FunctionKey		,"ファンクションキー"),
		new ActionInfo(JzEditorAction.Help				,"ヘルプ"),
		new ActionInfo(JzEditorAction.About				,"バージョン情報"),
		new ActionInfo(JzEditorAction.ScriptTest		,"スクリプトテスト"),
		new ActionInfo(JzEditorAction.SelectNextTab		,"次のタブ"),
		new ActionInfo(JzEditorAction.SelectPrevTab		,"前のタブ"),
		new ActionInfo(JzEditorAction.DosExec			,"シェルコマンド実行"),
		new ActionInfo(JzEditorAction.Option			,"オプション"),
		new ActionInfo(JzEditorAction.ShortCut			,"ショートカット"),
		new ActionInfo(JzEditorAction.Search			,"検索"),
		new ActionInfo(JzEditorAction.Replace			,"置換"),
		new ActionInfo(JzEditorAction.SelectDoc			,"文章の選択"),
		new ActionInfo(JzEditorAction.Grep				,"Grep"),
		new ActionInfo(JzEditorAction.JumpLine			,"指定行へジャンプ"),
		new ActionInfo(JzEditorAction.JumpPairKakko		,"対の括弧へジャンプ"),
		new ActionInfo(JzEditorAction.Compare			,"比較"),
		new ActionInfo(JzEditorAction.SearchDown		,"下へ検索"),
		new ActionInfo(JzEditorAction.SearchUp			,"上へ検索"),
		new ActionInfo(JzEditorAction.Remember			,"記憶"),
		new ActionInfo(JzEditorAction.ShowTab			,"タブ表示"),
		new ActionInfo(JzEditorAction.ShowRet			,"改行表示"),
		new ActionInfo(JzEditorAction.ShowEOF			,"EOF表示"),
		new ActionInfo(JzEditorAction.ShowBigSpace		,"全角スペース表示"),
		new ActionInfo(JzEditorAction.ShowSpace			,"スペース表示"),
		new ActionInfo(JzEditorAction.ShowLineNum		,"行番号表示"),
		new ActionInfo(JzEditorAction.ShowRuler			,"ルーラー表示"),
		new ActionInfo(JzEditorAction.NewBinary			,"新規バイナリ"),
		new ActionInfo(JzEditorAction.OpenBinary		,"バイナリで開く"),
		new ActionInfo(JzEditorAction.DebugBinEditor	,"バイナリデバッグ"),
		new ActionInfo(JzEditorAction.AutoTab			,"自動タブ"),
		new ActionInfo(JzEditorAction.SelectStart		,"選択開始"),
		new ActionInfo(JzEditorAction.FlipInsertMode	,"挿入モード"),
		new ActionInfo(JzEditorAction.MacroRecStart		,"マクロ記録開始"),
		new ActionInfo(JzEditorAction.MacroRecEnd		,"マクロ記録終了"),
		new ActionInfo(JzEditorAction.MacroRecToggle	,"マクロ記録開始/終了"),
		new ActionInfo(JzEditorAction.MacroPlay			,"マクロ再生"),
		
		new ActionInfo(JzEditorAction.InsertCopyString	,"最近コピーした文字列"),
		new ActionInfo(JzEditorAction.InsertSearchString,"最近検索した文字列"),
		new ActionInfo(JzEditorAction.InsertInputString	,"最近入力した文字列"),
		new ActionInfo(JzEditorAction.InsertDeleteString,"最近削除した文字列"),
		new ActionInfo(JzEditorAction.InsertDate		,"日付"),
		new ActionInfo(JzEditorAction.InsertFile		,"ファイル"),
		new ActionInfo(JzEditorAction.InsertFilename	,"ファイル名"),
		new ActionInfo(JzEditorAction.InsertHorizon		,"水平線"),
		new ActionInfo(JzEditorAction.InsertTable		,"表"),
		
	};
	public static ActionInfo[] getActionInfoTbl(){
		return g_actioninfo_tbl;
	}
}
